AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance in public subnet

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::RDS-EC2-keypair
    Description: Name of an existing EC2 KeyPair to enable SSH access

  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Latest Amazon Linux 2 AMI ID for the region


  ProjectName:
    Type: String
    Default: cf-ec2-rds-vpc-sns
    Description: Project name for tagging

  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - staging
    Description: Environment name

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref LatestAmiId
      SubnetId: !ImportValue Network-PublicSubnet1Id
      SecurityGroupIds:
        - !ImportValue SecurityGroup-EC2
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-ec2"

Outputs:
  EC2InstanceId:
    Description: EC2 instance ID
    Value: !Ref EC2Instance
    Export:
      Name: Compute-EC2InstanceId

  EC2PublicIp:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: Compute-EC2PublicIp
